### ISSUE TITLE
Data fetching broken since the last few days?

### ISSUE THREAD

**Issue by xfzv** [blackadderkate/weather-widget-2#98] opened 2022-05-17 18:25 UTC
- Distros: Arch Linux / Gentoo
- KDE Plasma version: 5.24.5-1
- Weather Widget 2 version: 2.2.2

The widget doesn't seem to fetch weather data properly since the last few days.

## With OpenWeatherMap
I'm getting the current temperature and the rain (+ forecast for both), but I'm not getting any weather condition (including forecast) at all, just "N/A".

## With Met.lo
The weather doesn't fetch any data at all. all I'm getting is this:

![image](https://user-images.githubusercontent.com/78810647/168883358-0604e565-c8f3-4136-b219-c28ef6ffaf25.png)

Rebooting doesn't make any difference. I can browse both [OpenWeatherMap](https://openweathermap.org/) and [met.no](https://www.met.no/en) websites just fine.

Just wondering if I'm the only one.

Thanks!

**Comment by blackadderkate** [comment] 2022-05-18 18:26
Have you installed any KDE updates recently? It could be issue #89 ...

**Comment by xfzv** [comment] 2022-05-18 19:02
Sorry, I totally missed that one (#89). Indeed, I've switched from `ksysguard` to `plasma-systemmonitor` (and added a few widgets to my panel) a few days ago. The issue started occurring from that moment.

Hopefully it'll be fixed with KDE Frameworks 5.95 coming on June 11th, I'll let you know.

Thank you. :+1:

**Comment by blackadderkate** [comment] 2022-05-19 17:55
I am keeping my fingers crossed for June 11th!
It has been very frustrating having KDE break my widget, and being completely unable to do anything about it...

Closed as a duplicate of #89 .

**Closed** 2022-05-19 17:55 UTC

**Comment by martin-ms** [comment] 2022-05-21 15:34
> Hopefully it'll be fixed with KDE Frameworks 5.95 coming on June 11th, I'll let you know.

If you are in hurry or can't wait, you can rebuilt the `kdeclarative`-package using the provided patch.  I did it and can confirm that it solves the problem.
